### ISSUE TITLE
画面共有ボタン押下時の、PopupComponentを実装する

### ISSUE THREAD

**Issue by yohachiSuga** [HiroakiTowata/mentor_proto#100]
- どの画面を共有するか選択できるPopup画面
- WebSocketで共有開始を送信する

**Comment by HiroakiTowata** [comment]
- PopupComponent は MediaPickerModal として実装。
- WebSocket での共有開始は、WebSockets.js で処理だけ追加した。handleDisplaySelected というコールバックでソース選択されたときに共有開始を行う想定(App-Front.js に暫定実装追加済)
