### ISSUE TITLE
ShareContainerを実装する

### ISSUE THREAD

**Issue by yohachiSuga** [HiroakiTowata/mentor_proto#102]
- 画面共有する背景画面の上にOperationComponentを描画
- OperationComponentは常に半透明で非active。トグルボタンみたいなのを押すとactiveになって、opacity=1になり、チャット記入などが可能になる

**Comment by HiroakiTowata** [comment]
結局画面を一枚で進めることができなかったので、OverlayScreen というものを追加して、それを透明にした。また、ShareContainer 自体はシェア開始時に右側に寄せるようにした。
