### ISSUE TITLE
音声通話機能

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#125]
音声通話はあくまでオプションのままだが、やはり音声のほうが早いということもありそう。

**Comment by yohachiSuga** [comment]
VideoAppのtrackAudioを制御すればいけるが、マイクのONOFF制御モーダルが必要かもしれない

**Comment by HiroakiTowata** [comment]
とりあえず、どれくらい大変かわからないけど、チャレンジしてみることにする。

**Comment by yohachiSuga** [comment]
とりあえずON/OFFできるところまでやってみる。
mentor-shareで完結できるのが理想的。

**Comment by yohachiSuga** [comment]
Mic/camera/audioInput/audioOutputの選択のサンプルを見つけたので真似ればいけそう。
electronだとAPIが少し変わるから、そこだけ注意すれば大丈夫そう
https://github.com/twilio/video-quickstart-js

**Comment by yohachiSuga** [comment]
１PCで音声通話の動作確認までできた。少しVideoAppの修正が必要。
音声品質があまり良くない（音が途切れているというかノイジー）が、原因は下記辺りかも。
・１台のPCでやってるから、ノイズが乗っかってる？？
・Twilioで音声通話品質とかを調整できるみたい。これをやる必要があるかも？

しっかり実装（メディア機器の選択画面含む）する場合、５時間以上はかかりそう。

**Comment by HiroakiTowata** [comment]
原因については確かにどちらも有り得そうだね。
5 時間とかで実装できるならぜひ入れたい機能ではあるよね。ただ、先に VideoApp の切り出しかな?

**Comment by yohachiSuga** [comment]
そうですね。LobbyContainerにも必要な機能なので、VideoAppの切り出しが先ですねー
メディア機器の選択くらいは先行して実装できる機能なので、そちらだけやっておきます！

**Comment by yohachiSuga** [comment]
Closeしちゃったけど、まだメディア選択完了後にTwilioと連携しないといけないのでReopen
