### ISSUE TITLE
チャットスクリーン第一版

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#13]
ルームは作れたので、チャットスクリーンで実際にやり取りできるところまで実装する。
「解決」「あきらめる」ボタンのいずれかで終了。
解決済 or 未解決でステータス更新
諦めたカウントをインクリメント

**Comment by yohachiSuga** [comment]
twilio-videoはv1.xとv2.xがあるが、互換性がない。
v2.xがβフェーズのため、今回はv2.xを使用する
