### ISSUE TITLE
VideoApp.tsxをライブラリとレンダリング機能で分割する

### ISSUE THREAD

**Issue by yohachiSuga** [HiroakiTowata/mentor_proto#139]
今のVideoApp.tsxは、RTC機能とDOMレンダリング/state保持が一緒くたになってる。
現在、RTCのバックエンドのTwilioを使っているが、PeerJS等への移行も踏まえて、そこをReplaceableにしておきたい。
そのために、RTC部とDOMレンダリング部に分割する

**Comment by yohachiSuga** [comment]
方針（仮）：
- VideoApp.tsxをVideoAppとTwilioLibにわける。
- TwilioLibは、WebSocketManagerみたいにシングルトンにしてどこからでも呼べるようにする（Toolpaletからも直接呼べるようにしたいから）
- DOM操作関連のメソッドは切り出しつつTwilioLibにコールバックで引き渡す感じにするのが良さそう。コールバックメソッド群はOptionalにしておいて、DOM操作をする必要がないコンポーネントからは何も引き渡さない。

**Comment by HiroakiTowata** [comment]
ついでにTwilioLib は WebRTCLib を継承する感じで作りますか。
