### ISSUE TITLE
WSでCompleteSessionを受信したときの動作を実装する

### ISSUE THREAD

**Issue by yohachiSuga** [HiroakiTowata/mentor_proto#141]
CompleteSessionByMentee/ByMentor受けた後に、通知を受けたことを表示する何かしらのModalを出す。
そのModalの後にRatingModalを出すように、実装する。
でいいはず。

**Comment by yohachiSuga** [comment]
@HiroakiTowata 
このイシューのユーザーフローについて確認させてください。
いくつか方法があると思うんですが、下記の流れでどうでしょう？
１．completeSessionBy***を受信したら、Modal表示。このModal内部には、GiveUp/ReolveButtonがあって、Matchの更新が可能
２．１でボタン押下後にRatingModalが開く
３．２でボタン押下後にFeedBackModalが開く（ユーザーテスト中のみ）

１＋２を合わせてモーダル出してもいいですが、どう思います？

**Comment by HiroakiTowata** [comment]
モーダルは分けておこう。
モーダル表示は Lobby だけに閉じ込めて、completeSessionBy*** を受信したら Lobby に必ず遷移するようにしてもいい気がする。
そうすると、Lobby で最初に matching の状態をみて、GiveUp/RosolveButton のあるモーダルを出す、RatingModal を出すって処理を変えればいい。でも、history.push で同じパスに飛ばした時はレンダリングされないような気もする。

**Comment by yohachiSuga** [comment]
モーダル分割は了解です。

>モーダル表示は Lobby だけに閉じ込めて、completeSessionBy*** を受信したら Lobby に必ず遷移するようにしてもいい気がする。
そうすると、Lobby で最初に matching の状態をみて、GiveUp/RosolveButton のあるモーダルを出す、RatingModal を出すって処理を変えればいい。でも、history.push で同じパスに飛ばした時はレンダリングされないような気もする。

先行して類似したアプローチで着手してましたー。たしかにLobbyに遷移させて、そこに処理集約するのもありだとは思います。
自分の方で、GiveUpButton/ResolveButtonとRatingModalをContainerでwrapした感じにして、Modalでも何でも再利用性高く表示できるようにしてあります。
completeSessionBy***を受信したら、そのContainerを含むModalを表示しようかな、と思ってました。
コード見ないとよくわからんと思うので、WIPですが先行して出しておきますー

**Comment by HiroakiTowata** [comment]
方針はこれでいいと思うんだけど、いったんクローズしたんだね。

**Comment by yohachiSuga** [comment]
WIP作ったつもりが、WIPになってなかったので一旦クローズしましたー
また再度オープンします！
