### ISSUE TITLE
シェアされてる側の共有画面を大きく表示する

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#150]
コメント(Operation Panel)はかなり端に表示すればオーケーで、ボタン押下で非表示にしちゃう。
音声有効の場合はそもそも表示しなくていいし。

**Comment by yohachiSuga** [comment]
チャットは非表示賛成ですー。
「解決・諦める」ボタンは、ツールパレット同様に非表示にさせないほうがいいと思うんですが、認識あってます？

**Comment by HiroakiTowata** [comment]
んー、チャットごと非表示にもっていってもいいかもよ？そんないきなり終わりたいか微妙なとこかな。

**Comment by yohachiSuga** [comment]
たしかにそうですねー、解決・諦めるボタンを押す前は最後にチャットしそうですし。
解決・諦めるボタンも非表示にできるように実装進めてみます。

**Comment by yohachiSuga** [comment]
PRで一旦できたが、下記が未完了
- スクロールバーを非表示化
スクロールバーを隠したいが、position:relativeにするとれいあうとがもろもろ崩れる
　　
- チャットが一部はみ出てる
sendButtonがはみ出てる

- Toolpaletの位置がおかしい

**Comment by yohachiSuga** [comment]
チャットは、ReactBootstrapのComponentを変更して対応完
