### ISSUE TITLE
シェアされている側が、シェア開始できない

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#151]
A 側でシェア開始
A 側でシェア停止
B 側でシェア開始... されない

**Comment by yohachiSuga** [comment]
あ、これは普通に未実装でした。
ユーザーフローもあるので、一旦脇においてました。
下記のフローで考えてましたが、擦り合わさせてください。
1. A側でシェア開始
2. B側でシェア開始
3. 「A側に通知、A側がシェア状態なら何かダイアログを出す。AcceptしたらAでシェアを自動的に停止して、Bのシェアを開始させる？」 or 「B側で相手がシェアしていたら、シェア開始できないようにする（Bが、Aに共有を止めるようなアクション（チャットとか）を起こさせる）」とかとか。

**Comment by HiroakiTowata** [comment]
シェアしてる途中でできないのはまぁいいんだけど、相手がシェア完了時にこちらがシェア開始できないのは普通に何かステートがおかしいのだと思う。
まずはダイアログとか無しで後勝ちでいい気がする。
- シェアリング要求受信
- (もしシェア中なら)シェア停止
- シェア受信画面へ移行

これですごくシンプルじゃない?
