### ISSUE TITLE
Web と Electron のワークフローを再度整理する

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#160]
- Lobby までは共通として、OperationPanel に画面共有開始ボタンを置くか置かないかを isElectron 状態で切り替える
- 上記のため、Lobby への Routing は Web 側でも追加する
- Sharing Screen への Routing は Web 側には追加しない
- Shared Screen への Routing は Web 側に**追加する** (設計上動作可能か要確認)
- また、Web 側の場合は、「画面共有するためにはアプリをダウンロード」ボタンを置く
- WebSocket の通知先は Web と Electron の後勝ちになる(Electron 操作中に Web を操作してしまうと、通知先として持っていかれてしまう可能性はあるところに注意)

**Comment by HiroakiTowata** [comment]
LobbyContainer, Shared Screen, Sharing Screen それぞれがかなり mentor-desktop 側に依存していることがわかった。切り出すのがけっこう難しいので、一旦 Web 側からは上記への遷移は諦めて、マッチング以降は基本的にダウンロードページに飛ばすこととする。

**Comment by HiroakiTowata** [comment]
将来的な方向として、SharingScreen, MediaPicker, OverlayScreen だけを mentor-desktop 側にのこして、ほかは全部 mentor-share 側に移す。OperationPanel から MediaPicker を切り離して、SharingScreen にうつしてしまう。
あと SharedScreen から ElectronMode を外す。たぶんこれで依存関係が切れる。

**Comment by yohachiSuga** [comment]
実装方針は下記で決定。リファクタは別Issueで。 #166 で実施
https://github.com/HiroakiTowata/mentor_proto/issues/160#issuecomment-599277942
