### ISSUE TITLE
SharedScreenでSharing側のユーザーのRatingを見れてしまう

### ISSUE THREAD

**Issue by yohachiSuga** [HiroakiTowata/mentor_proto#163]
[problem]
- SharedScreenで、SharingUserが相手を評価してるところが見れてしまう。

[solution]
- SharingScreen.tsxでratingModalを表示する前に、overlayScreenをdestroyさせる

**Comment by HiroakiTowata** [comment]
というか、終了ボタン押した瞬間にシェアリングを止めればいいはず。
OverlayScreen はただの表示なので。
