### ISSUE TITLE
user のプロパティが user.name やら user.nickname やらで混じっている

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#185]
たぶん、user.firstname, user.lastname, user.nickname みたいな感じにして、表示は nickname にするべき。あと、プロファイル情報が入力されてないときは強制的に modal 表示とかで入力させるようにしたい。

**Comment by yohachiSuga** [comment]
userプロパティ自体ごちゃごちゃしてきたので一回見直したいですね。
