### ISSUE TITLE
OverlayScreen 上にシェア停止等のメニューを表示する

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#199]
シェア中のオペパネはあんまり見ない気がするので、OverlayScreen 上にプルダウンとかで表示したい。
- シェア停止
- 音声停止
- などなど

**Comment by yohachiSuga** [comment]
>シェア中のオペパネはあんまり見ない気がするので、OverlayScreen 上にプルダウンとかで表示したい。

WebSocketの通知がオペパネに来てるので、それもOverlayScreenに出したほうがユーザーフレンドリーかもですね
