### ISSUE TITLE
セッション後のリザルト画面

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#20]
相手を評価する
相手をメンターとして登録する
相手をメンティとして登録する

これによってメンター一覧画面が出せるようになる。(いまは固定データで表示してるだけ)
2画面で、メンターとメンティ共通部分をコンポーネントにする。

**Comment by HiroakiTowata** [comment]
これでレーティングは簡単にやれそう。
https://github.com/Rudolph-Miller/react-bootstrap-star-rating

**Comment by yohachiSuga** [comment]
これ担当していいですか？
このタスクなら、ウェブソケットの部分と作業が競合しなさそうなので！

**Comment by HiroakiTowata** [comment]
とてもいいと思います！

**Comment by yohachiSuga** [comment]
画面遷移が多いので、リザルト画面はModal表示で実装予定。
Modalの裏の画面は、HOMEもしくはシェア画面。

**Comment by yohachiSuga** [comment]
実装したのでクローズ
