### ISSUE TITLE
メンティーからメンターが「教えて」依頼を受けた時、トピックの内容を表示

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#211]
そもそもそのメンターが答えられる内容かどうかがわからないから、トピックの内容を表示してあげる。
また、断られたときにいきなりメンティー側でモーダルを閉じるのはなくて、断られた理由も含めて表示する。「いまは忙しい」「そのトピックには答えられない」「気分が乗らない」などなど。

**Comment by yohachiSuga** [comment]
>「いまは忙しい」「そのトピックには答えられない」「気分が乗らない」などなど

クイックレスポンスみたいに、ボタン一個クリックで相手に通知できると良さそうです！
