### ISSUE TITLE
ElasticSearchService の追加

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#247]
ES はちょっとコストが高いので、お金を節約するために、local 実行、dev 環境、stage 環境は共有することにしたい。各ステージごとに index を分けるイメージ。

**前提**
現在、scan もしくは query で DynamoDB からデータを取得しているがそろそろフィルタリング・クエリが柔軟に欲しくなってきたので、ES を導入する。

**設計**
基本的に DynamoDB と ES は DynamoDB streams + Lambda で同期するものとする。CRUD のうち、R だけを ES にして、その他は引き続き DynamoDB を利用する。また、hashkey, rangekey で取得する get はそのまま DynamoDB を直接コールするものとする。

**要検討項目**
- DynamoDB Local との整合性。それぞれのデバッグ時にデータが混じると不整合がでてきてしまうので、それぞれの環境で ES の Docker を動かして Local 実行時、migration フォルダ以下のデータを ES に流し込むこととする。
- index 設計。基本的にはステージごとに index を分けるイメージ。ただし、今後の商用利用におけるマルチテナント化を考えると、index はステージごとかつテナントごとに分けるべき。(所属とは違う)

**Comment by yohachiSuga** [comment]
serverless offline dynamodb streams が動かない問題は、下記PRのMerge/Relase待ち
https://github.com/CoorpAcademy/serverless-plugins/pull/125

**Comment by HiroakiTowata** [comment]
#255 によりクローズ済
