### ISSUE TITLE
画面のお絵かきも含めて、画面デザイン(設計)を決める

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#63]
- Twilio のお絵かき機能調査
- マウスオーバーで出したり消したりできるツールバー
- ツールバーを使ってチャットウィンドウを出したり消したりする

**Comment by yohachiSuga** [comment]
https://github.com/twilio/draw-with-twilio

**Comment by HiroakiTowata** [comment]
シェアする側は OverlayScreen 全体表示 + コメント等は右側寄せ。シェアされる側は Video をできるだけ大きく表示 + フルスクリーン。
