### ISSUE TITLE
Windows のインストーラを Github Actions でアップロードする

### ISSUE THREAD

**Issue by HiroakiTowata** [HiroakiTowata/mentor_proto#73]
インストーラができるように Electron を構成する

**Comment by HiroakiTowata** [comment]
Mac のインストーラー作成はできている。要 Windows 対応。

**Comment by HiroakiTowata** [comment]
Mac 版はできているので、Windows 版で下記対応すること。
- Windows のインストーラーの動作確認
- Github Actions でアーティファクトとして保存

**Comment by HiroakiTowata** [comment]
動いてるかも確認

**Comment by yohachiSuga** [comment]
Windowsでインストーラで正式にインストールして起動確認OK。
ビデオシェアリングが行えていることも確認OK。
あとはインストラーのアップロード
